apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hub-platform
  namespace: {{ .Values.gitops.namespace }}
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - list:
        elements:
{{- range .Values.operators }}
          - name: {{ .name | quote }}
            path: {{ .path | quote }}
            valuesFile: values/mgmt.yaml
            namespace: {{ .namespace | quote }}
            wave: {{ .wave | quote }}
{{- end }}
  template:
    metadata:
      name: '{{ `{{.name}}` }}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{ `{{.wave}}` }}'
    spec:
      project: {{ .Values.gitops.project }}
      source:
        repoURL: {{ .Values.gitops.repoURL }}
        targetRevision: {{ .Values.gitops.targetRevision }}
        path: '{{ `{{.path}}` }}'
        helm:
          valueFiles:
            - '{{ `{{.valuesFile}}` }}'
      destination:
        server: {{ .Values.gitops.destinationServer }}
        namespace: '{{ `{{.namespace}}` }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
{{- if .Values.gitops.preserveResourcesOnDeletion }}
      preserveResourcesOnDeletion: true
{{- end }}
